const articles = [
  {
    id: 1,
    blogTitle: "Un Poco de Energía 101",
    blogDescription:
      "¿Cansado de pagar altas facturas de energía y preocupado por el medio ambiente? Este artículo te explica de manera sencilla cómo la energía está presente en todos los aspectos de nuestra vida y cómo podemos tomar el control. Desde consejos prácticos para ahorrar en gasolina hasta la importancia de adoptar energías renovables en nuestros hogares, descubrirás cómo hacer una diferencia en tu bolsillo y en el planeta. ¡Aprende a optimizar tu consumo energético y a vivir de forma más sostenible!",
    blogContent: [
      "Decidir el tema de esta columna fue complicado, ya que me considero “celoso” y selectivo cuando quiero educarme o educar.",
      "Luce que el asunto de la energía está muy de moda y existe una considerable cantidad de información y artículos muy completos y competentes. Sin embargo, seguí ponderando opciones hasta que entendí que definitivamente la “ENERGÍA sí está de moda”, porque nos interesa, porque ha sido protagonista en drenar los bolsillos de mi amado Puerto Rico y porque sin ella no podemos vivir.",
      "Al transformarla, nos afectamos positiva o negativamente y, de igual forma, a nuestro terruño más grande llamado Planeta Tierra. Pues definamos que la energía, de manera simple y no apta para los didácticos del tema, es la capacidad de la materia en hacer un trabajo o de hacer que algo cambie, ya sea bajo un movimiento, reacción química, temperatura, etc.",
      "A mis escasos 12 años, cuando cursaba el séptimo grado, decidí que quería ser ingeniero. Recuerdo como hoy cuando en una feria de ciencias de mi Escuela René Marqués, en Carolina, llevé alrededor de 10 carros a escala, todos de mi colección que aún conservo. Expuse diferentes aspectos del diseño de la carrocería y expliqué cómo eso influía en la aerodinámica de los autos y, por consiguiente, en el consumo de la gasolina. Obviamente, a mi nivel académico de ese entonces, y quizás con algunas “metidas de pata” que los jueces no quisieron divulgar, recuerdo haberme sentido orgulloso de mi participación, y aprendí mucho con el proyecto.",
      "Unos seis años más tarde, siendo “prepa” en el Recinto de Mayagüez de la UPR, recuerdo que un profesor me dijo: “La energía no se crea ni se destruye, solo se transforma”. Probablemente, usted que me lee también ha escuchado esto y, aunque confuso, es cierto. Pero como no pretendo aburrirlos con principios termodinámicos, mejor echémosle un poco de arroz, habichuelas y carne guisada a este escrito.",
      "Cuando usted llena el tanque de gasolina en su automóvil, aparte de recordarse de las “cruditas” (en plural), también recuerda cómo reinventarse para que le rinda más. Por mencionar algunos solamente, entre ese tanque, el motor, la transmisión, y las gomas, existe una transformación de energía en diferentes tipos, la cual tiene el fin de mover su auto y a usted. Dicha transformación emplea muchos temas eléctricos y mecánicos para llevarlos a su lugar deseado.",
      "La gasolina es un combustible fósil derivado del petróleo. Y un combustible fósil es uno formado naturalmente hace muchos años, de compuestos orgánicos como animales y plantas. Al considerarse que estos no pueden ser reemplazados rápidamente, se les cataloga como no renovables. De igual forma, al utilizarse y quemarse, en la mayoría de los casos afectan grandemente nuestro medioambiente.",
      "En línea con estos planteamientos, paso entonces a unos puntos que considero prácticos y pertinentes:",
      "1. Edúquese basándose en su escenario, por ejemplo, en la transportación. Asumamos que usted maneja su auto un promedio de 250 millas semanales y que este tiene una clasificación de 17 MPG (millas por galón de gasolina). Si tiene la oportunidad de cambiar su auto por uno que rinda 25 MPG, y asumiendo un costo de gasolina de $1/litro, lo cual equivale a $3.78/galón, estaría ahorrando alrededor de $80 mensuales. De igual forma, puede evaluar un auto eléctrico o híbrido. Reconozco que aún los costos no son tan accesibles para gran parte de los puertorriqueños, pero traen muchos beneficios en gastos recurrentes y en nuestro entorno ambiental.",
      "2. Evalúe opciones de sistemas fotovoltaicos en su residencia o negocio. Al igual que con la tecnología de autos eléctricos, esta aún no es accesible a muchos ciudadanos, pero ya existen distintas alternativas que, orientadas por un profesional competente en la materia, tanto en la ingeniería como en las finanzas, pudiesen ser viables para muchos.",
      "3. Simplifique lo que defino como “costumbres energéticas”. No solo es empezar a “cambiar” equipos, autos, tecnologías, sino también comenzar a desarrollar una mejor conciencia ambiental y conducta energética. El solo apagar una luz, andar varias personas en un mismo vehículo, o prender un solo aire acondicionado al disfrutar de una buena película en familia, se traduce en conservación de vida a corto, mediano y largo plazo y, de igual forma, alivia el bolsillo.",
      "4. Plante un árbol, camine, recicle, reutilice, haga composta, abra ventanas, piense cómo ayudar el ambiente cada día, e impleméntelo. Agradezco a la filosofía de María Montessori, la cual se pensará que no tiene que ver con energía, más, sin embargo, está directamente relacionada.",
      "Morocho, a quien, al igual que a Margot, le dedico esta mi primera columna, me dijo algo que nunca he olvidado: “El conocimiento jamás es un desperdicio”. Creo mucho en la educación y por eso les insto a que se sigan educando en este tema. Es muy relevante en estos momentos y toda persona, a todo nivel, puede educarse para bien.",
    ],
    blogDate: "Mayo 24, 2022",
    blogArticle: "/education-un-poco-de-energia-101",
    blogSource:
      "https://www.elvocero.com/opinion/columnas/un-poco-de-energ-a-101/article_44378e2a-daf3-11ec-a7e7-afbcf2e620a7.html",
    blogSourceName: "El Vocero",
    authorName: "Geraldo Peña Guzmán",
    authorTitle: "Ingeniero",
    authorImg: "",
  },
  {
    id: 2,
    blogTitle: "Energía 102",
    blogDescription:
      "¿Estás pensando en invertir en energía solar para tu hogar o negocio? Este artículo te guía paso a paso para que tomes la mejor decisión. Aprenderás cómo evaluar tu consumo energético actual, seleccionar el sistema solar adecuado y considerar factores como los eventos naturales. Además, descubrirás los beneficios a largo plazo de adoptar energías renovables, tanto para tu bolsillo como para el medio ambiente. ¡Convierte tu hogar en uno más sostenible y autosuficiente!",
    blogContent: [
      "En una pasada columna titulada Un poco de energía 101, definí el concepto de energía de la manera más simple que entendí posible, y expuse algunas sugerencias de ahorro. Ahora, y más con todos los sucesos recientes en Puerto Rico y el mundo, veo prudente sugerir a todos la adopción de otras fuentes de energía. Sé que esto se ha mencionado mucho últimamente, pero en mi opinión, se debe seguir analizando e informando sobre este tema medular.",
      "Si seguimos dependiendo de los combustibles fósiles, seguirá siendo imposible mantener el control de los costos de producción de energía y, por consiguiente, tampoco se podrá ofrecer tarifas competitivas y estables a los consumidores. De igual forma, nuestro ambiente seguirá afectándose a un nivel innecesario y perjudicial.",
      "Reconozco que, en la mayoría de los casos, si evaluamos la inversión de estas tecnologías renovables únicamente con la lupa financiera, no siempre son costo efectivas. Pero, cuando ampliamos nuestra mira hacia otros aspectos, comprendemos que se trata de un tipo de inversión rentable, recomendable y necesaria.",
      "Por eso, con un poco de arroz, habichuelas, y carne guisada, aquí unas recomendaciones para cuando usted comience a evaluar posibilidades de inversión en energía renovable para su residencia o negocio, principalmente del tipo fotovoltaica:",
      "1. Haga un análisis de su estilo de vida en el uso de energía. ¿Qué puede apagar? ¿Qué equipo puede utilizar con menos frecuencia? ¿Qué equipo puede utilizar de manera más eficiente? Por ejemplo, aquí en el trópico, el solo incrementar 2 grados Fahrenheit la temperatura deseada en su acondicionador de aire, puede reflejar una reducción considerable en el consumo energético.",
      "2. Reduzca su consumo. Se entiende que aún existen altos costos en los sistemas renovables. Por tanto, primero se recomienda invertir en equipos más eficientes y luego diseñar y seleccionar el tamaño idóneo del sistema. Algunos ejemplos son: cambiar el calentador de agua eléctrico y de tanque por uno solar o de línea; instalar acondicionadores de aire más eficientes o con tecnología “inverter”; cambiar bombillas incandescentes o fluorescentes por bombillas tipo “LED”; aislar techos o paredes; cambiar algunos enseres por unos de mayor eficiencia, entre otras iniciativas. Mayormente, para el caso de edificios comerciales o industriales, también recomiendo integrar sistemas de controladores automatizados. Quizás no es necesario que adopte todas las sugerencias de reducción de consumo, sino que evalúe cuáles de estas le serían viables, e implementarlas. Tomar una o dos, redundará en beneficio económico a la hora de seleccionar su sistema renovable.",
      "3. Mida su consumo real actual. Aparte de las lecturas o estimados que pueden observar en su factura eléctrica, pudiesen también medir su consumo utilizando otros tipos de medidores locales. Investigue esta tarea con un ingeniero, perito electricista, o con la empresa de su preferencia, con quien estaría evaluando la instalación de su sistema. Si es posible, hágalo en diferentes momentos del año y estudie los datos de todos los meses anteriores, utilizando sus facturas eléctricas. Se preguntarán el porqué de todos modos sugiero medir el consumo, si ya este debe mostrarse en la factura. Pero, al menos aquí en Puerto Rico, he visto muchos casos donde el tener esa segunda confirmación es definitivamente recomendable.",
      "4. Piense y evalúe sus condiciones actuales o futuras. Por ejemplo, hay hijos que se mudan de la casa de sus padres y, en muchas ocasiones, esto podemos conocerlo de antemano. El tener una persona menos en el hogar, probablemente redunde en menor consumo energético. O, por el contrario, hay casos donde la familia crecerá, donde se desea ampliar la casa o construirle una piscina. Con esta información a la mano, podríamos contemplar ese estatus futuro de consumo. Todo se calcula y se puede estimar, y su profesional seleccionado debe saber cómo hacerlo.",
      "5. Evalúe los embates de huracanes y otros tipos de eventos naturales. Debe decidir cuáles son sus prioridades. Aquí algunas preguntas que debe hacerse: ¿quiere la casa o negocio completamente encendido, o puede energizar solo las cargas que necesita como prioridad?, ¿cuál es su presupuesto?, ¿cuánto tiempo puede operar solo con baterías, asumiendo luz solar nula o muy poca?, entre algunas otras que se pueden plantear junto con su profesional seleccionado. Debido al huracán Fiona, muchos consumidores experimentaron problemas con sus sistemas solares, ya que prácticamente no recibimos sol considerable por alrededor de dos días. De igual forma, hubo muchos problemas con sistemas que quedaron sin almacenamiento de energía, y luego no podían encenderse automáticamente con la luz solar, sino que requerían de un proceso manual que solo conocían los expertos. Debe preguntar todo esto, y cuestionar los posibles escenarios y medidas para limitar dichos problemas.",
      "Pero de serle posible, y aquí sabemos que entran temas económicos y geográficos que se deben evaluar, por mencionar algunos, sea parte de la transformación energética que necesita su hogar, su negocio, y el País. Sus pasos firmes y efectivos en estos temas, redundarán en beneficio individual y colectivo tanto local como mundial. El planeta tiene una necesidad imperiosa de adoptar mejores tecnologías de producción, manejo, y uso de energía. Voy a usted…",
    ],
    blogDate: "Noviembre 17, 2022",
    blogArticle: "/education-energia-102",
    blogSource:
      "https://www.elvocero.com/opinion/columnas/energ-a-102/article_88f579b4-6612-11ed-9432-3779c8b5af3f.html",
    blogSourceName: "El Vocero",
    authorName: "Geraldo Peña Guzmán",
    authorTitle: "Ingeniero",
    authorImg: "",
  },
];

export default articles;
